### ISSUE TITLE
Some files not included in code coverage

### ISSUE THREAD

**Issue by brainmonger** [Bubbit/wct-istanbub#10]
I have a file which is not being included in the coverage unless I include a `<link rel="">`. I'm using `"**/*.html"` in my includes list and have even tried including the file explicitly, but still it will not get covered since it doesn't contain a `<link rel="">`. Is this an issue or am I missing something?

**Comment by Bubbit** [comment]
Which version of wct-istanbub are you using? the 0.2.0.pre- version or the last stable one?

I ran into a similar issue for the last pre version (PR is open), but want to know if it's an old issue or new ^^

**Comment by brainmonger** [comment]
@Bubbit confirmed the issue I saw was with `0.2.0-pre.4`. I wanted to try with `0.2.0` but am on a different laptop now and seeing a different error `Error thrown outside of test function` which I'm guessing is unrelated.

**Comment by brainmonger** [comment]
Hi @Bubbit, I asked another dev to test out version `0.2.0` and it turns out switching to that version causes the `Error thrown outside of test function` error for him as well. Any ideas? I'm not sure which version to use.. at least `0.2.0-pre.4` runs for us except it has that missing file from coverage issue I first mentioned.

**Comment by Bubbit** [comment]
I didn't publish 0.2.0 yet, so you used the branch? I have saved time tomorrow to do a deep-dive on it during work hours, so I'll start up a bigger project with polymer 3 (my current project is still polymer 2 due to work setup etc)

**Comment by brainmonger** [comment]
@Bubbit ah yes, I just pulled in the `0.2.0` branch. We are still on Polymer 2 as well.

**Comment by Bubbit** [comment]
I've just updated the branch, I ran into the issue with the polymer 3 starter kit app, with some 'tests' added. 

It was related due to the hacky replace that needs to be done with the new version of istanbulJS (still need to create an issue on the repo).

Can you give it a try and see if it fixes your issue? -> https://github.com/Bubbit/wct-istanbub/pull/9/commits/c40f302cd570975e8a91f1726d41a89ac3768236#diff-d7dfcb350720309421bbb465055aafdfR28

**Comment by brainmonger** [comment]
@Bubbit Nice, this update seems to work! I can now see the missing file in our code coverage after installing with `npm install git://github.com/Bubbit/wct-istanbub/tree/istanbuljs#istanbuljs`
