### ISSUE TITLE
Cannot install via npm

### ISSUE THREAD

**Issue by eavichay** [Bubbit/wct-istanbub#11]
OS: Windows 10

```
>npm install wct-istanbub --save-dev
npm ERR! code E404
npm ERR! 404 Not Found: babylon@^7.0.0-beta.42

npm ERR! A complete log of this run can be found in ....:
```

**Comment by Bubbit** [comment]
Which version of wct-istanbub is it trying to install? the 0.2.0.pre- version or the last stable one?

**Comment by eavichay** [comment]
Update: I get the same error for other installations that require the same dependency. It looks like a problem in the company's npm registry.

Thank you for fast response!
