### ISSUE TITLE
Current version does not support polymer 3 applications.

### ISSUE THREAD

**Issue by FaahdNoor** [Bubbit/wct-istanbub#12]

**Comment by Bubbit** [comment]
The last released version 0.2.0 does support Polymer 3, at least I tested it with the polymer-starter-application of polymer 3, what doesn't work?

**Comment by FaahdNoor** [comment]
is there some additional configuration for polymer 3, when i add istanbub in the wct.conf the test cases start failing with the following error.
`Object.wrapMethod at /components/ at polymer/sinonjs/sinon.js:1474:0
              Object.stub at /components/ at polymer/sinonjs/sinon.js:3528:0`

**Comment by Bubbit** [comment]
Shouldn't have to do anything, as the config for WCT is taken into account (npm -> true, for polymer 3 apps)

**Comment by Bubbit** [comment]
Closed due to inactivity
