### ISSUE TITLE
include option is modified

### ISSUE THREAD

**Issue by justincy** [Bubbit/wct-istanbub#7]
The `include` option is modified. Why? One would assume that devs would set `include` and `exclude` globs to sufficiently limit files.

https://github.com/Bubbit/wct-istanbub/blob/master/lib/middleware.js#L105-L118

If I submitted a PR to change this, how would you prefer that it be handled? Remove the modifications or add an option to skip the modification?

**Comment by Bubbit** [comment]
That was done related to: https://github.com/Bubbit/wct-istanbub/issues/1, if you still have use-cases in order to remove the default modification I would opt for the 2nd approach, adding an option to skip it :)
